baseURL = 'https://yarburart.github.io/'
languageCode = 'en-us'
title = 'YarBurArt'

author = "YarBurArt"
copyright = "YarBurArt"
pagination.pagerSize = 10
theme = "blowfish"
enableRobotsTXT = true
enableEmoji = true

[markup]
  _merge = "deep"

[params]
  #keywords = "Python, C#, C, Java, JavaScript, web services, scripts, bots, Linux, bash, automation, cybersecurity, security, code security, server security, DevOps, system administration, penetration testing, vulnerability research, secure coding, backend, SRE, CTF, writeup, walkthrough, red team, blue team, reverse engineering, forensics, capture the flag"
  keywords = ["Python", "C#", "C", "Java", "JavaScript", "web services", "scripts", "bots", "Linux", "bash", "automation", "cybersecurity", "security", "code security", "server security", "DevOps", "system administration", "penetration testing", "vulnerability research", "secure coding", "backend", "SRE", "CTF", "writeup", "walkthrough", "red team", "blue team", "reverse engineering", "forensics", "capture the flag"]
  subtitle = "Blog"
  contentTypeName = "posts"
  showAuthor = true

  [params.author]
    name = "YarBurArt"
    email = "yaroslav.chayk@gmail.com"
    image = "img/author-logo.png"
    headline = "Developer on python / C# and Security Specialist"  
    links = [
    { github = "https://github.com/yarburart" },
    { mastodon = "https://infosec.exchange/@datashiper" },
    ]

  [params.header]
    logo = "logo.svg"
    title = " yarburart"

  [params.footer]
    since = 2025
    poweredby = true

  [[params.social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/yarburart'

  [params.homepage]
    layout = 'profile'
    showRecent = true
    showMoreLink = true
    showMoreLinkDest = '/writeup/'
    showRecentItems = 6
    # todo homepageImage
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = false 
  
  [params.article]
    showTableOfContents = true
 
[menu]

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    pageRef = "posts"
    weight = 10
  [[menu.main]]
    identifier = "writeup"
    name = "Writeups"
    pageRef = "writeup"
    weight = 15
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pageRef = "tags"
    weight = 30
  [[menu.footer]]
    name = "CV | About"
    pageRef = "cv"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
